runtime: ruby27
env: standard
service: portfolio
entrypoint: mkdir -p tmp/pids && bundle exec rackup --port $PORT

automatic_scaling:
  min_instances: 0
  max_instances: 1
  min_idle_instances: automatic
  max_idle_instances: automatic
  min_pending_latency: automatic
  max_pending_latency: automatic

env_variables:
  SECRET_KEY_BASE: ee22092a1e3bc2a2da839b83297554b705a35a31458c18c8b201ccbc69d69e601989a416b39a00ba3e28e59675a4702012b30354fe11d7cb90e83e4b6d937be0